targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
      drift_dev:
        options:
          generate_connect_constructor: true
          use_data_class_name_for_companions: true