targets:
  freezed_only:
    auto_apply_builders: false
    builders:
      freezed:
        enabled: true
  $default:
    dependencies: [ ":freezed_only" ]
    builders:
      freezed:
        enabled: false
      json_serializable:
        options:
          field_rename: snake
      drift_dev:
        options:
          use_data_class_name_for_companions: true