name: e1547
description: A sophisticated e621 browser
version: 21.0.0-from-rubble+95
publish_to: none

environment:
  sdk: ">=3.6.2 <4.0.0"
  flutter: ">=3.27.4 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  context_plus: ^4.1.4
  deep_pick: ^1.1.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_sub: ^3.0.0
  fquery: 1.5.4-beta.2
  freezed_annotation: ^3.0.0
  infinite_scroll_pagination: ^5.0.0
  json_annotation: ^4.9.0
  meta: ^1.15.0
  shared_preferences: ^2.5.2

# dart run build_runner build
# dart run flutter_launcher_icons
# dart run flutter_native_splash:create
dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.25.2
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app/
    - assets/static/
  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/font/JetBrainsMono-Regular.ttf
        - asset: assets/font/JetBrainsMono-Italic.ttf
          style: italic
        - asset: assets/font/JetBrainsMono-Bold.ttf
          weight: 700

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  adaptive_icon_background: "assets/icon/app/background.png"
  adaptive_icon_foreground: "assets/icon/app/foreground.png"
  image_path: "assets/icon/app/icon.png"
  windows:
    generate: false
    image_path: "assets/icon/app/round.png"
    icon_size: 256

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "000000"
  image: "assets/icon/app/round.png"

cider:
  link_template:
    tag: https://github.com/clragon/e1547/releases/tag/%tag%
    diff: https://github.com/clragon/e1547/compare/%from%...%to%
