name: e1547
description: Dragon's e1547 fork.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:

  esys_flutter_share: ^1.0.2
  url_launcher: ^5.4.2

  like_button: ^0.2.0
  photo_view: ^0.9.2
  cached_network_image: ^2.0.0
  flutter_staggered_grid_view: ^0.3.0

  permission_handler: ^4.3.0
  shared_preferences: ^0.5.6

  flutter_launcher_icons: ^0.7.4

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:

  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/paw.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/paw.png
