name: e1547
description: A mobile app for e621+e926.

version: 1.2.1+11

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:

  icon_shadow: ^1.0.1
  flutter_parsed_text: ^1.2.4
  url_launcher: ^5.4.2

  like_button: ^0.2.0
  photo_view: ^0.9.2
  video_player: ^0.10.8+1
  cached_network_image: ^2.0.0
  flutter_staggered_grid_view: ^0.3.0

  permission_handler: ^4.3.0
  shared_preferences: ^0.5.6

  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9
  flutter_statusbarcolor: ^0.2.3

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:

  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/paw.png"


flutter_native_splash:
  image: "assets/icon/paw.png"
  color: "000000"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/paw.png
