name: e1547
description: A mobile app for e621+e926.
version: 12.0.0+61
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:

  # widgets
  async_builder: ^1.3.1
  cached_network_image: ^3.2.1
  decorated_icon: ^1.2.0
  expandable: ^5.0.1
  flutter_cache_manager: ^3.3.0
  flutter_custom_tabs: ^1.0.4
  flutter_screen_lock: ^7.0.2
  flutter_staggered_grid_view: ^0.6.2
  flutter_typeahead: ^4.0.0
  font_awesome_flutter: ^10.1.0
  grouped_list: ^5.1.2
  like_button: ^2.0.4
  local_auth: ^2.0.2
  overflow_view: ^0.3.1
  photo_view: ^0.14.0
  provider: ^6.0.3
  pull_to_refresh: ^2.0.0
  sliding_sheet: ^0.5.0
  sliver_tools: ^0.2.7
  video_player: ^2.4.5

  # data
  app_links: ^3.0.2
  async: ^2.9.0
  collection: ^1.15.0
  crypto: ^3.0.1
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.0
  dio_cache_interceptor_db_store: ^5.0.0
  drift: ^2.0.2
  external_path: ^1.0.1
  filesize: ^2.0.1
  freezed_annotation: ^2.0.3
  image_gallery_saver: ^1.7.1
  intl: ^0.17.0
  media_scanner: ^2.1.0
  mutex: ^3.0.0
  package_info_plus: ^1.4.2
  path: ^1.8.1
  path_provider: ^2.0.11
  path_to_regexp: ^0.4.0
  permission_handler: ^10.0.0
  pub_semver: ^2.1.1
  relative_time: ^2.0.1
  share_plus: ^4.0.10
  shared_preferences: ^2.0.11
  sqflite: ^2.0.2+1
  sqflite_common_ffi: ^2.1.0
  sqlite3_flutter_libs: ^0.5.0
  store_checker: ^1.0.0
  talker: ^1.0.0+1
  url_launcher: ^6.1.3
  wakelock: ^0.6.1+2
  window_manager: ^0.2.5

  infinite_scroll_pagination:
    git: https://github.com/clragon/infinite_scroll_pagination.git
  username_generator:
    git: https://github.com/clragon/username_generator.git

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^2.2.2

  # dart run build_runner build
  build_runner: ^2.1.11
  drift_dev: ^2.0.1
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/round.png

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  adaptive_icon_background: "assets/icon/app/background.png"
  adaptive_icon_foreground: "assets/icon/app/foreground.png"
  image_path: "assets/icon/app/icon.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "000000"
  image: "assets/icon/app/round.png"