name: e1547
description: A mobile app for e621+e926.
version: 10.1.3+59
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:

  # widgets
  expandable: ^5.0.1
  like_button: ^2.0.4
  photo_view: ^0.13.0
  grouped_list: ^4.1.0
  video_player: ^2.3.0
  sliver_tools: ^0.2.5
  overflow_view: ^0.3.1
  sliding_sheet: ^0.5.0
  decorated_icon: ^1.2.0
  pull_to_refresh: ^2.0.0
  flutter_typeahead: ^3.2.4
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^10.1.0
  flutter_cache_manager: ^3.3.0
  flutter_staggered_grid_view: ^0.4.1 # 5.x.x-6.x.x is breaking

  # data
  dio: ^4.0.6
  share: ^2.0.1
  intl: ^0.17.0
  mutex: ^3.0.0
  crypto: ^3.0.1
  timeago: ^3.1.0
  filesize: ^2.0.1
  wakelock: ^0.6.1+2
  collection: ^1.15.0
  store_checker: ^1.0.0
  url_launcher: ^6.0.17
  dio_http_cache: ^0.3.0
  package_info_plus: 1.3.0 # 1.3.1-1.4.x is broken
  permission_handler: ^9.2.0
  sqflite_common_ffi: ^2.1.0
  shared_preferences: ^2.0.11
  image_gallery_saver: ^1.7.1

  infinite_scroll_pagination:
    git: https://github.com/clragon/infinite_scroll_pagination.git
  media_scanner:
    git: https://github.com/clragon/media_scanner.git
  username_generator:
    git: https://github.com/clragon/username_generator.git

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon/round.png

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  adaptive_icon_background: "assets/icon/app/background.png"
  adaptive_icon_foreground: "assets/icon/app/foreground.png"
  image_path: "assets/icon/app/icon.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "000000"
  image: "assets/icon/app/round.png"