name: e1547
description: A mobile app for e621+e926.

version: 1.6.2+35

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:

  expandable: ^4.1.3
  flutter_typeahead: ^1.8.0
  pull_to_refresh: ^1.5.8
  icon_shadow: ^1.0.1
  like_button: ^1.0.1
  flutter_staggered_grid_view: ^0.3.0

  video_player: ^0.11.0
  photo_view:
    git:
      url: https://github.com/fireslime/photo_view.git
      ref: master
  cached_network_image: ^2.3.2

  http_auth: ^0.3.0
  url_launcher: ^5.5.3
  share: ^0.6.3+6
  intl: ^0.16.1

  permission_handler: ^5.0.1+1
  shared_preferences: ^0.5.6

  flutter_launcher_icons: ^0.8.0
  flutter_native_splash: ^0.1.9
  flutter_statusbarcolor: ^0.2.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:

  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/paw.png"


flutter_native_splash:
  image: "assets/icon/paw.png"
  color: "000000"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/paw.png
