name: e1547
description: A mobile app for browsing e926.net and friends.

dependencies:
  # Mine
  zoomable_image:
    git: git://github.com/perlatus/flutter_zoomable_image.git

  # Third party
  cached_network_image:
    path: ../fork/flutter_cached_network_image
  flutter_cache_manager:
    path: ../fork/flutter_cache_manager

  flutter_staggered_grid_view: 0.1.3
  font_awesome_flutter: 6.0.0
  simple_permissions: 0.1.3

  # Dart
  http: 0.11.3+16
  logging: 0.11.3+1
  meta: 1.1.5
  test: 0.12.37
  vector_math: 2.0.6

  # Flutter
  share:
    path: ../fork/flutter_plugins/packages/share
  shared_preferences: 0.4.1
  url_launcher: 3.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - icons/paw.png
