blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/MRwKGqfmUz
    about: Questions? Ask in the discord server
  - name: Email
    url: mailto:kenta3ds.habbo@gmail.com
    about: You can reach me via Email
