name: Application Release

on:
  release:
    types: [published]

jobs:
  ios-build:
    runs-on: macos-latest
    steps:
      - name: setup actions
        uses: actions/checkout@v3

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: get dependencies
        run: flutter pub get

      - name: build release
        run: flutter build ios --no-codesign

      - name: package release
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/Runner.app
          zip -9 -r e1547.zip Payload
          mv e1547.zip ../../../e1547.ipa

      - name: upload release to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-ios
          path: e1547.ipa

      - name: upload release to assets
        uses: softprops/action-gh-release@v1
        with:
          files: e1547.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: setup actions
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "12"

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: configure release keys
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYCONFIG: ${{ secrets.KEYCONFIG }}
        run: |
          mkdir -p android/app/keys
          echo "$KEYSTORE" | base64 -d > android/keys/key.pkcs
          echo "$KEYCONFIG" | base64 -d > android/keys/key.properties

      - name: get dependencies
        run: flutter pub get

      - name: build release
        run: flutter build apk

      - name: package release
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk e1547.apk

      - name: upload release to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: e1547.apk

      - name: upload release to assets
        uses: softprops/action-gh-release@v1
        with:
          files: e1547.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
